version: '3'
services:
  node_app:
    build: 
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
    depends_on:
      - python_app
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development

  python_app:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    command:
       tail -f /dev/null
